groups:
  - name: capacity_planning
    rules:
      - record: service:cpu_usage:rate5m
        expr: sum(rate(container_cpu_usage_seconds_total{image!=""}[5m])) by (name)
      - record: service:memory_usage:bytes
        expr: sum(container_memory_usage_bytes{image!=""}) by (name)
      - record: service:network_io:bytes_total
        expr: sum(container_network_receive_bytes_total{image!=""} + container_network_transmit_bytes_total{image!=""}) by (name)
      - record: service:restarts:total
        expr: sum(container_restarts_total{image!=""}) by (name)
