global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'fastapi-services'
    static_configs:
      - targets: ['auth-service:8000','user-service:8001','product-service:8002','order-service:8003','chat-service:8005','api-gateway:8080']
